### ISSUE TITLE
Does this template comply to ASU style specifications about TOC headings? and PDF example to view?

### ISSUE THREAD

**Issue by russelljjarvis** [GarenSidonius/ASU-Dissertation-Template#24]
Hi Garen,

This looks awesome. I am struggling away with the older ASU dissertation template. Particularly I am having trouble getting the headings of TOC correct as specified by the the style guide, and the upper margin of TOC correct too.

I wonder where I can see an example pdf in order to check if your template would solve my problems?

I am using the older template and it could take me about a day to re-apply your code.

https://github.com/russelljjarvis/DataDrivenOptimizationASU

**Comment by russelljjarvis** [comment]
I switched to your template and I find it better satisfies ASU style especially regarding TOC LOF LOT. I think of a group of people who have used your template should demand that your version be made into the official ASU overleaf template, that is generated from the formatting tool.

The current supported template is unusable.

**Comment by GarenSidonius** [comment]
Hi @russelljjarvis , this template should meet the guidelines in ASU's formatting guide, including for the table of contents, list of figures, and list of tables. I don't get any kind of notification when people use the template, but some people are using it, and I haven't heard that they had problems with that aspect of the template. Also, I used an early version of the template on my own dissertation, and that passed format review.

You can build a sample document yourself if you are familiar with Docker: 

1. Install Docker on your computer.
2. Run `./build.sh`
3. Run `./latexmk.sh -pdf -xelatex dissertation_template_latex_sample.tex`

You can build the sample without Docker, too; it's just that I've created images to make it easy with Docker.

> I think of a group of people who have used your template should demand that your version be made into the official ASU overleaf template

This template is intentionally not on Overleaf, but people can upload it into their personal projects on Overleaf if they want to use it there.

I'm not sure what graduate students see when they work with ASU's formatting tool, but the GitHub repo for ASU's current template ( https://github.com/shumway/asudis ) refers to my repo here in the first sentence, so hopefully people are at least aware of this template as an option.

**Comment by GarenSidonius** [comment]
@russelljjarvis , let me know if you get stuck with making the sample PDF, and I'll see if I can help.

**Comment by russelljjarvis** [comment]
Actually the template renders, but I am having trouble making the appendix table of contents to specification.

**Comment by GarenSidonius** [comment]
@russelljjarvis The file that you're using `dis_new.tex` seems to have a lot of edits that could change the way appendices are handled (e.g., https://github.com/russelljjarvis/DataDrivenOptimizationASU/blob/ae474883441812be2bf23aa2fd70e6c2c7384926/dis_new.tex#L1324 ). 

To get the most out of the template, I would recommend to copy the file `dissertation_template_latex.tex` into your project and edit it per instructions in the file; that is, leave it mostly alone and just edit lines where indicated with `%<` and `%~`. Add only required packages in the preamble, and add TeX files that need to be imported in the body. (Try to import as few packages as possible because LaTeX packages can interact with each other in surprising ways.)

I did some experiments with the template and found that including multiple appendices seems to work better with `\input` rather than `\include` (contrary to the advice in the template). Here are the edits to `dissertation_template_latex.tex` to demo:
```
diff --git a/dissertation_template_latex_sample.tex b/dissertation_template_latex_sample.tex
index 6c83d4b..0b63b27 100644
--- a/dissertation_template_latex_sample.tex
+++ b/dissertation_template_latex_sample.tex
@@ -1268,7 +1268,8 @@
 %\include{appendix3}% etc.               %   All heading commands are the same as above,
                                          %   e.g., \chapter, \section, etc.
 \iftoggle{sample}{%
-  \include{src/sample/appendix}%
+  \input{src/sample/appendix}%
+  \input{src/sample/appendix}%
 }{}
 
 \backmatter                             % Start back matter according to documentclass
```

Render with the following command:
```
$ ./latexmk.sh perl /usr/local/bin/latexmk/latexmk.pl -cd -interaction=batchmode -pdf -xelatex dissertation_template_latex_sample.tex
```

To get the following PDF:

[dissertation_template_latex_sample.pdf](https://github.com/GarenSidonius/ASU-Dissertation-Template/files/5576921/dissertation_template_latex_sample.pdf)

Notice that the appendices have several levels of headings, but the appendices appear correctly in the table of contents and in the back matter.

Does that help move things along?

**Comment by russelljjarvis** [comment]
Thanks yes, I diffed the original template dissertation_template_latex_sample.tex with my current one, which helped me find the lines which included unnecessary headings, I then used `input` instead of `include`, and I got expected output.

The reason my code became so divergent from your original template, is I rapidly developed and merged with a conflicting template.

I see you created an issue about bookdown. Does this mean in the future your template will support thesis down and Rmarkdown? I personally would have preferred the Rmarkdown route.

**Comment by GarenSidonius** [comment]
@russelljjarvis It sounds like we might be able to close this issue. Is there anything else that's needed?

Regarding R support, my plan was to add bookdown support; I'm not familiar with thesis down, but I'll look into that when I get to that point and consider doing that instead. (Just by the way, don't expect any of that stuff to be done any time soon since I don't have a ton of time to build new features like that.)
