### ISSUE TITLE
Not compiling on Windows, tried miktex, tinytex as well as docker

### ISSUE THREAD

**Issue by vipin8169** [GarenSidonius/ASU-Dissertation-Template#27]
Hello, I am using this template and it works excellent on Overleaf. However, my thesis has a lots of images because of which the requests time out on Overleaf. Therefore, I have to work in draft mode in which images are rendered as an empty box.

So, for getting a version with images, I need to compile it on my local machine. However, it is not compiling and keeps giving errors. I have tries using [MikTex](https://tex.stackexchange.com/questions/584146/miktex-extractpdftexversion-has-an-extra?noredirect=1#comment1468407_584146) (latest version) and [Tinytex ](https://tex.stackexchange.com/questions/584150/missing-number-treated-as-zero-for-ifnumcomp-in-tinytex-using-r)using R on windows. But it is not working. Kindly help!

EDIT: Since miktex did not work, I tried Docker and it gave error too. Installed the Docker for first time ever, ran the `./build.sh` which led to error
=> ERROR [1/3] FROM docker.io/blang/latex:ubuntu@sha256:2c32abc3555a01  701.9s
failed to register layer: Error processing tar file(exit status 1): write /usr/s
hare/texmf/fonts/type1/public/tex-gyre/qplr.pfb: read-only file system

![image](https://user-images.githubusercontent.com/4578304/108569158-9f812a00-72c8-11eb-9c20-38235af8a34b.png)

**Comment by GarenSidonius** [comment]
Hi @vipin8169 , it's hard for me to say because I don't run Windows myself. However, from Googling around on your error it looks like some people had luck after restarting their docker service (or just restarting their computer) or by modifying permissions of some of the files and folders involved. If you Google the problem and try some of those solutions, are you able to get it to work?

**Comment by GarenSidonius** [comment]
Closing as stale
