### ISSUE TITLE
How to use the template with Miktex and Tex Studio

### ISSUE THREAD

**Issue by abshafique** [GarenSidonius/ASU-Dissertation-Template#4]
I have been trying quite a bit to compile this template with TexStudio and Miktex. Have not been able to get to the output yet. It keeps saying xetex.def cannot be found, I spent quite a while to find that package and had to manually add it to miktex. Then it complained about certain math packages and expl3 packages and kernel. Finally when I finished all that, now it has a number of errors. I tried pdflatex, xelatex and latexmk in TexStudio.

Please, I need help compiling this template on some platform. I am willing to zip the current project directory to you so you can have a look. I'm attaching a screenshot of the errors produced.

![untitled](https://cloud.githubusercontent.com/assets/9476390/17500126/7da624ea-5d87-11e6-93ae-0edd190b6c5f.png)

FYI: I also tried with TexnicCenter and the same problems are happening.

**Comment by GarenSidonius** [comment]
It's very difficult to troubleshoot people's local LaTeX installations, which is one of the reasons I give instructions on using ShareLaTeX. If you post your documents to ShareLaTeX and share them with me (robert@kutterconsulting.com), I will take a look: https://www.sharelatex.com/learn/Sharing_your_work_with_others

**Comment by abshafique** [comment]
On Sharelatex it is compiling fine. So is it on Overleaf. However, I have many images and I was worried that it will take a long time to compile which is why I wanted it working locally. Also, every file needs to be uploaded which is quite inconvenient for such a large document. It's strange that Miktex does not have the packages that the template requires. I had to add many of them manually.

I shared the Sharelatex project with you.

**Comment by GarenSidonius** [comment]
If you're able to build your document with the template on ShareLaTeX, then I think you're set. 

You may have to download additional packages through TeXLive to get it working on MiKTeX -- I don't know which version of that you've installed. Again, this is why I've provided instructions on using the template with ShareLaTeX (because it's not really practical for me to troubleshoot issues with people's local TeX installations). 

Since there are no issues with the template and you're able to produce a PDF, I'm closing this issue. 

For troubleshooting issues with TeX itself, there are other resources, such as http://tex.stackexchange.com/.
