### ISSUE TITLE
 Changing header on second page of Table of Contents from 'References' to 'CHAPTER.'

### ISSUE THREAD

**Issue by abshafique** [GarenSidonius/ASU-Dissertation-Template#9]
On second page of Table of Contents, the header says 'References' instead of 'CHAPTER.' Asu dissertation checkers pointed this out. How do I fix it?
![capture](https://cloud.githubusercontent.com/assets/9476390/18846517/2600d896-83db-11e6-8fa5-d4838ea6a1c0.PNG)

Also, the  subheadings and sub-subheadings in the Table of Contents must be in title case. Is there a way to automate this process?

**Comment by GarenSidonius** [comment]
Issue #1: I pushed an update so that the heading on all subsequent TOC pages should be "CHAPTER". 

Issue #2: All caps sub-headings does not fit the formatting guide that is currently posted: See [here](https://graduate.asu.edu/format-manual), and click on "table of contents (chapter format)". If someone at the formatting office is telling you to make sub-headings in all caps, please point them to the posted format manual. 

(In the future, go ahead and open two tickets for two different issues. It makes it easier to organize.)
